### PR TITLE
Fixed print statements and xrange to be compatibile with Python 2 and 3.

### PR DESCRIPTION
**Pull request by dennisobrien**
A few minor changes to make the example code in `guide/` and `test/` work in Python 2 and 3.  This addresses issue #54 

Unfortunately I have not tested this since it's not clear how to build and test this module independently.  If I missed this docs, please point me in the right direction and I'd be happy to do what I can to run the tests locally.

thanks,
Dennis

### CODE REVIEW

**Comment by innovia** [comment]
can someone please fix the issue here - the build from source  fails on this annoying error and thie PR needs to be merged

**Comment by innovia** [comment]
Thank you!

**Comment by innovia** [comment]
@tqchen can you please advance the submodule for rabit on the xgboost master ? pulling xgboost with recursive gets the old commit of rabbit 
```
Submodule path 'rabit': checked out 'a764d45cfb438cc9f15cf47ce586c02ff2c65d0f'
```

**Comment by tqchen** [comment]
PLease send a pr

**Pull request merged**
