### PR TITLE
Fix ssize_t definition.

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis Do we need this for XGBoost?

**Comment by trivialfis** [comment]
@hcho3 Yes.  I need to upgrade rabit for xgboost.  Will address the linter.

**Comment by trivialfis** [comment]
@hcho3 Any chance that you can add a appvayor test for rabit?  I'm currently relying on to make sure this PR is done right: https://github.com/dmlc/xgboost/pull/4159

**Comment by trivialfis** [comment]
And by the way, if there's need to address the linter in `dmlc-core`, we should write a script to do so ...

**Pull request merged**
