### PR TITLE
Set a minimal reducer size and parent_down size

### PR DESCRIPTION
**Pull request by FelixYBW**
currently distributed xgboost's performance varies largely run to run even we tried to input exact the same partition into each worker. Its performance is more than 2x poor if we wrongly config to use 1GbE network (It's another issue we need to fix), or if we run on a IPoIB network.

The root cause is that sometimes a message is broken into two pieces when a child receives it, but the second piece has a long wait up to >10 ms, while the network is empty actually.
Looks like the poll(-1) caused this issue but I set it to poll(0)+pause which doesn't help.

image

This happens more frequently on 1GbE network and IPoIB, which leads to even poor performance.

The fix is to set a minimal reducer size as N Byte, so every time parent can reduce and pass down the N Byte message at least. Then child can wait until receiving N Byte. In our test, xgboos uses allreduce(sum), the real calculation time is very little so we can set it upto 1MB which is bigger than the maximal msage size of our workload.

image

### CODE REVIEW

**Comment by FelixYBW** [comment]
I did an experiment of epoll, but performance is the same even if I use edge_trigger. We still need the busy recv fix here. A epoll_wait + recv still leads to delays. 
Some questions are still open:
- It mainly happens on parent_down. Not frequently happen on receiving child_up.
- This fix solved most of the delay, but not all. Sometimes the whole message is delayed.  It may because the network hardware delay (less likely) or because OS scheduling.
- Why the busy poll (poll with 0 timeout) doesn't solve the problem.

**Comment by trivialfis** [comment]
Let me fix the travis tests.

**Comment by trivialfis** [comment]
CI should be fixed in https://github.com/dmlc/rabit/pull/140 .

**Comment by FelixYBW** [comment]
what's the error? style check on my local machine passed.

src/engine_mpi.cc:13:  Found C++ system header after other system header. Should be: engine_mpi.h, c system, c++ system, other.  

The file isn't touched.

11 #define NOMINMAX
12 #include <mpi.h>
13 #include <cstdio>
14 #include "rabit/internal/engine.h"

**Comment by hcho3** [comment]
Cpplint 1.5.0 is released last week and it changed the way it checks the header order.

**Comment by hcho3** [comment]
CI is fixed in #141

**Comment by FelixYBW** [comment]
Passed eventually. It's odd I have to move <mpi.h> before <cstdio>. Added <string>
fix allreduce_base.cc's header seq

**Comment by FelixYBW** [comment]
@trivialfis @hcho3 

Any comments on the PR? Can we merge it?

**Comment by hcho3** [comment]
@FelixYBW Was this change tested in a production cluster with XGBoost (or other application)?

**Comment by FelixYBW** [comment]
> @FelixYBW Was this change tested in a production cluster with XGBoost (or other application)?

Yes, it's tested in several clusters with xgboost training.

**Comment by FelixYBW** [comment]
> @FelixYBW Was this change tested in a production cluster with XGBoost (or other application)? I ask this question because the plot you posted shows only the time for sending messages. The CI set up here may not detect all possible ways this change can break XGBoost.
> 
> > In our test, xgboos uses allreduce(sum), the real calculation time is very little so we can set it upto 1MB which is bigger than the maximal msage size of our workload.
> 
> Can I take it as that you tested with XGBoost? How is the impact on the end-to-end training performance?

Yes, we tested on xgboost. It works well so far. The chart in the first post is the end2end xgboost training performance improvement on 3 clusters with 4 nodes in each cluster but using different network. The dataset is a 600M Row x 46 columns one. Also the patch makes xgboost training time much more stable.

**Comment by hcho3** [comment]
> The chart in the first post is the end2end xgboost training performance improvement on 3 clusters with 4 nodes in each cluster but using different network.

@FelixYBW Nice, thanks for clarifying. 1.5-3x boost end-to-end is quite nice.

**Comment by hcho3** [comment]
@FelixYBW Merged. Thanks! I'll file a pull request to use this commit in XGBoost.

**Pull request merged**
