### PR TITLE
add retry mechanism to ConnectTracker and modify Listen backlog to 128 in rabit_traker.py

### PR DESCRIPTION
**Pull request by daiyl0320**
issue描述详见https://github.com/dmlc/xgboost/issues/544

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for the contribution!

**Comment by daiyl0320** [comment]
：）

**Comment by tqchen** [comment]
Thanks for your contribution, I have added you to https://github.com/dmlc/xgboost/blob/master/CONTRIBUTORS.md Please feel free to open PR to add more details about you.

You are also welcomed to contribute further changes to make xgboost and rabit better:)

**Comment by daiyl0320** [comment]
thx

**Comment by daiyl0320** [comment]
thx

**Pull request merged**
