### PR TITLE
allow timeout to 0 for immediate exit

### PR DESCRIPTION
**Pull request by chenqin**
@CodingCat

### CODE REVIEW

**Comment by chenqin** [comment]
@trivialfis @hcho3 oneliner

**Comment by CodingCat** [comment]
what does  immediate exit  mean here?

**Comment by chenqin** [comment]
when rabit worker observed peers socket error, it starts countdown and exit if failed worker fail to connect before timeout expire. This is causing issues with xgb4j-spark jobs where we observed worker see retry timeout because we close sparkcontext without before rabit agent and agent keep ping already closed tracker. 
https://github.com/dmlc/rabit/blob/master/src/allreduce_robust.cc#L641

we when set timeout=0 all worker will failure at same time if a worker dead. It also helps with testing in xgb4j-spark side and simulate graceful failure handling.

**Comment by CodingCat** [comment]
> close sparkcontext before rabit agent and agent keep ping already closed tracker. 

when we close SparkContext, executors will quit, therefore the tasks in executor side will also quit, and rabit worker is running in a thread of executors, why it can keep pinging tracker?

**Comment by CodingCat** [comment]
per offline, LGTM

**Pull request merged**
